---
title: "The spectral properties of a pH-sensitive probe accumulated in cytoplasmic puncta in HeLa cells change by flowing of the cells with medium, as evidenced using a novel image analysis algorithm."
subtitle: "R code for the statistical processing" 
author: "Vadim Pérez Koldenkovaa, Yasel Garcés Suárez, Tomoki Matsudaa, Adán Guerreroc, Takeharu Nagai"
date: "March 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## General information


## Load data files
```{r,message=FALSE}
# Necessary Library
library(dplyr)
library(ggplot2)
library(plotly)
library(reshape2)
library(gridExtra)
library(cowplot)

# Load the scrip of functions.
source("Functions.R")

#----------------------------------------------------------------------------
## Load the files for the 3 conditions
# Directory with the data
dir_GR_Quenching<-'/home/yasel/TRABAJO/Adan_Lisosomas/Data(csv)/GR quenching/'
dir_R_no_Quenching<-'/home/yasel/TRABAJO/Adan_Lisosomas/Data(csv)/R_no_quenching/'
dir_GR_no_Quenching<-'/home/yasel/TRABAJO/Adan_Lisosomas/Data(csv)/GR_no_quenching/'

# Load data
GR_Quenching<-readFiles(dir_GR_Quenching)
R_no_Quenching<-readFiles(dir_R_no_Quenching)
GR_no_Quenching<-readFiles(dir_GR_no_Quenching)
#----------------------------------------------------------------------------
# Include the condition in the data and merge all conditions.
GR_Quenching<-mutate(GR_Quenching,Condition='GR Quenching')
R_no_Quenching<-mutate(R_no_Quenching,Condition='R no Quenching')
GR_no_Quenching<-mutate(GR_no_Quenching,Condition='GR no Quenching')

# Merge data
GlobalData<-rbind(GR_Quenching,R_no_Quenching,GR_no_Quenching)

# Some variables need to be converted to factors.
GlobalData$Time.Img<-as.factor(5*GlobalData$Time.Img) # times 5 
GlobalData$No..Cell<-as.factor(GlobalData$No..Cell)
GlobalData$Condition<-as.factor(GlobalData$Condition)
GlobalData$Video<-as.factor(GlobalData$Video)
```

## PLots
```{r,message=FALSE}
# Number of lysosomes by time and Condition.
LysosomesNumber <- summarise(group_by(GlobalData, Time.Img,Condition), 
                        No.Lyso=max(No..Lys.))
LysosomesNumber$Time.Img<-as.numeric(as.character(LysosomesNumber$Time.Img))
p1<-ggplot(LysosomesNumber,aes(x=Time.Img,y=No.Lyso,
                               color=Condition))+geom_point()+geom_line()+xlab('Time')+
        ylab('Number of Lysosomes')+theme(legend.position="bottom")+
        scale_y_continuous(breaks = seq(0, 200, by = 20))+
        scale_x_continuous(limits = c(0, 605),breaks = seq(0, 600, by = 50))
ggplotly(p1,width = 1000)
```

Resume all the information by cells, that is, for each cell we compute the number of lysosomes, the time, mean of the area, perimeter mean, intensity mean, integral intensity mean and mean of intensity over the area.
```{r,message=FALSE}
# Resume data
GlobalData <- summarise(group_by(GlobalData, Time.Img,Condition), mCherry = mean(mCherry_Mean.), 
                        Sd_mCherry=sd(mCherry_Mean.), Venus=mean(Venus_Mean), 
                        Sd_Venus=sd(Venus_Mean), Area=mean(Area.Lys.)*0.21,
                        Sd_Area=sd(Area.Lys.),
                        mCherry_over_Area=mean(mCherry_Mean./Area.Lys.), 
                        Sd_mCherry_over_Area=sd(mCherry_Mean./Area.Lys.),
                        Venus_over_Area=mean(Venus_Mean/Area.Lys.),
                        Sd_Venus_over_Area=sd(Venus_Mean/Area.Lys.),
                        Venus_over_mCherry=mean(Venus_Mean/mCherry_Mean.),
                        Sd_Venus_over_mCherry=sd(Venus_Mean/mCherry_Mean.))
#---------------------------------------------------------------------------
############################################################################
# Study of the mean intensity by channel and R no Quenching and GR no Quenching conditions.

mean_intensity<-select(GlobalData,Time.Img,mCherry,Venus,Condition)
mean_intensity <- melt(mean_intensity,id=c("Time.Img","Condition")) # convert to long format

mean_intensity_SD<-select(GlobalData,Time.Img,Sd_mCherry,Sd_Venus,Condition)
mean_intensity_SD<-melt(mean_intensity_SD,id=c("Time.Img","Condition")) # convert to long format
colnames(mean_intensity_SD)<-c("Time.Img","Condition","variable1","sd_value")

mean_intensity <- merge(mean_intensity, mean_intensity_SD)
colnames(mean_intensity)<-c('Time.Img','Condition','Channel','value','variable1','sd_value')
# Channel mCherry
update_geom_defaults("point", list(size=0.1))
```

```{r,message=FALSE,fig.width=10}
# Generate the plots with different axis limits
occuplot <- plotfunc(mean_intensity, "GR no Quenching", -150, 1950)+
        theme(plot.margin=unit(c(0.1,0.3,0,-.5), "cm"))+
        scale_x_continuous(limits = c(0, 605),breaks = seq(0, 600, by = 100))
qualplot <- plotfunc(mean_intensity, "R no Quenching", -150, 1950)+
        theme(plot.margin=unit(c(0.1,0.3,0,-.5), "cm"))+
        scale_x_continuous(limits = c(0, 605),breaks = seq(0, 600, by = 100))
p3 <- plotfunc(mean_intensity, "GR Quenching", -150, 1950)+
        theme(plot.margin=unit(c(0.1,0.1,0,0), "cm"))+
        scale_x_continuous(limits = c(0, 605),breaks = seq(0, 600, by = 100))

# Extract the legend
mylegend<-g_legend(occuplot)

# Plot all the information in a same graphics.
plotG<-grid.arrange(arrangeGrob(p3+theme(legend.position="none"),occuplot+
                                        theme(legend.position="none")+ylab(""),
                                qualplot+theme(legend.justification=c(0,1),
                                        legend.position=c(0.2,1))+
                                 ylab(""),nrow = 1))
############################################################################
# Study the Venus/mCherry values for all conditions
mean_quotient<-select(GlobalData,Time.Img,Venus_over_mCherry,Condition)
mean_quotient <- melt(mean_quotient,id=c("Time.Img","Condition")) # convert to long format

mean_quotient_SD<-select(GlobalData,Time.Img,Sd_Venus_over_mCherry,Condition)
mean_quotient_SD<-melt(mean_quotient_SD,id=c("Time.Img","Condition")) # convert to long format
colnames(mean_quotient_SD)<-c("Time.Img","Condition","variable1","sd_value")

mean_quotient <- merge(mean_quotient, mean_quotient_SD)
colnames(mean_quotient)<-c('Time.Img','Condition','Channel','value','variable1','sd_value')

# The plot
# Generate the plots with different axis limits
p1<-ggplot(mean_quotient,aes(x=as.numeric(as.character(Time.Img)),y=value,color=Condition))+
        geom_ribbon(aes(ymax = value + sd_value, ymin= value - sd_value,fill = Condition),
                    linetype=0,alpha=0.2)+coord_cartesian(ylim=c(0.1, 1))+
        scale_y_continuous(breaks = seq(0, 1, by = 0.1))
p1<-p1+geom_point()+geom_line()+xlab('Time')+ylab('Venus/mCherry')+theme(legend.position="bottom")+
        scale_x_continuous(limits = c(0, 605),breaks = seq(0, 600, by = 50))
ggplotly(p1)
############################################################################
#---------------------------------------------------------------------------
# Study of the area by condition.

area<-select(GlobalData,Time.Img,Area,Condition)

ggplot(area, aes(Area, fill = Condition))+geom_density(alpha = 0.5)+
        xlab(expression(Area~(mu~m^2)))+
        ylab('Lysosomes Number')+theme(legend.position = c(0.8, 0.9))+
        scale_x_continuous(limits = c(0.29, 0.5),breaks = seq(0.29, 0.5, by = 0.05))
#---------------------------------------------------------------------------
```